# nova_engine/modules/sitebuilder/generator.py

import os

def generate_site(project_name, pages, features, base_path="generated_sites"):
    site_path = os.path.join(base_path, project_name)
    os.makedirs(site_path, exist_ok=True)

    # Create basic index.html
    with open(os.path.join(site_path, "index.html"), "w") as f:
        f.write(f"""
<!DOCTYPE html>
<html>
<head>
    <title>{project_name}</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>Welcome to {project_name}!</h1>
    <p>This site was generated by Nova.</p>
</body>
</html>
        """.strip())

    # Create other pages
    for page in pages:
        if page != "home":
            with open(os.path.join(site_path, f"{page}.html"), "w") as f:
                f.write(f"<h1>{page.capitalize()} Page</h1><p>Content for {page}.</p>")

    return site_path
